# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI="6"

DESCRIPTION="Meta package for various libretro implementations"
HOMEPAGE="http://www.libretro.com/"
LICENSE="metapackage"
SLOT="0"
IUSE="2048 3dengine 4do 81 atari800 beetle-psx bluemsx bnes bsnes bsnes-cpp98 cannonball cap32 chailove citra craft \
	crocods daphne desmume desmume2014 desmume2015 dolphin dosbox easyrpg fbalpha fbalpha2012 fbalpha2012-cps1 fbalpha2012-cps2 fbalpha2012-cps3 \
	fbalpha2012-neogeo fbneo fceumm flycast fmsx freeintv fuse gambatte gearboy genplus gme gpsp gw handy hatari ishiiruka \
	lutro mame mame2000 mame2003 mame2003plus mame2010 mame2015 mame2016 mednafen-gba mednafen-lynx mednafen-ngp mednafen-pce-fast \
	mednafen-pcfx mednafen-psx mednafen-saturn mednafen-snes mednafen-supergrafx mednafen-vb mednafen-wswan melonds meowpc98 meteor mgba mrboom \
	mupen64plus nestopia np2kai nxengine o2em openlara parallel-n64 pcsx-rearmed picodrive play pokemini ppsspp prboom prosystem px68k \
	quasi quicknes redream reicast reminiscence sameboy scummvm snes9x snes9x2002 snes9x2005 snes9x2010 stella tgbdual theodore
	thepowdertoy tyrquake vba-next vbam vecx vice virtualjaguar xrick yabause"

KEYWORDS=""

RDEPEND="2048? ( >=games-emulation/2048-libretro-9999 )
		3dengine? ( >=games-emulation/3dengine-libretro-9999 )
		4do? ( >=games-emulation/4do-libretro-9999 )
		81? ( >=games-emulation/81-libretro-9999 )
		atari800? ( >=games-emulation/atari800-libretro-9999 )
		beetle-psx? ( >=games-emulation/beetle-psx-libretro-9999 )
		bluemsx? ( >=games-emulation/bluemsx-libretro-9999 )
		bnes? ( >=games-emulation/bnes-libretro-9999 )
		bsnes? ( >=games-emulation/bsnes-libretro-9999 )
		bsnes-cpp98? ( >=games-emulation/bsnes-libretro-cplusplus98-9999 )
		cannonball? ( >=games-emulation/cannonball-libretro-9999 )
		cap32? ( >=games-emulation/cap32-libretro-9999 )
		chailove? ( >=games-emulation/chailove-libretro-9999 )
		citra? ( >=games-emulation/citra-libretro-9999 )
		craft? ( >=games-emulation/craft-libretro-9999 )
		crocods? ( >=games-emulation/crocods-libretro-9999 )
		daphne? ( >=games-emulation/daphne-libretro-9999 )
		desmume? ( >=games-emulation/desmume-libretro-9999 )
		desmume2014? ( >=games-emulation/desmume2014-libretro-9999 )
		desmume2015? ( >=games-emulation/desmume2015-libretro-9999 )
		dolphin? ( >=games-emulation/dolphin-libretro-9999 )
		dosbox? ( >=games-emulation/dosbox-libretro-9999 )
		easyrpg? ( >=games-emulation/easyrpg-libretro-9999 )
		fbalpha? ( >=games-emulation/fbalpha-libretro-9999 )
		fbalpha2012? ( >=games-emulation/fbalpha2012-libretro-9999 )
		fbalpha2012-cps1? ( >=games-emulation/fbalpha2012-cps1-libretro-9999 )
		fbalpha2012-cps2? ( >=games-emulation/fbalpha2012-cps2-libretro-9999 )
		fbalpha2012-cps3? ( >=games-emulation/fbalpha2012-cps3-libretro-9999 )
		fbalpha2012-neogeo? ( >=games-emulation/fbalpha2012-neogeo-libretro-9999 )
		fbneo? ( >=games-emulation/fbneo-libretro-9999 )
		fceumm? ( || ( >=games-emulation/fceumm-libretro-9999 >=games-emulation/fceu-next-libretro-9999 ) )
		flycast? ( >=games-emulation/flycast-libretro-9999 )
		fmsx? ( >=games-emulation/fmsx-libretro-9999 )
		freeintv? ( >=games-emulation/freeintv-libretro-9999 )
		fuse? ( >=games-emulation/fuse-libretro-9999 )
		gambatte? ( >=games-emulation/gambatte-libretro-9999 )
		gearboy? ( >=games-emulation/gearboy-libretro-9999 )
		genplus? ( >=games-emulation/genplus-libretro-9999 )
		gme? ( >=games-emulation/gme-libretro-9999 )
		gpsp? ( >=games-emulation/gpsp-libretro-9999 )
		gw? ( >=games-emulation/gw-libretro-9999 )
		handy? ( >=games-emulation/handy-libretro-9999 )
		hatari? ( >=games-emulation/hatari-libretro-9999 )
		ishiiruka? ( >=games-emulation/ishiiruka-libretro-9999 )
		lutro? ( >=games-emulation/lutro-libretro-9999 )
		mame? ( >=games-emulation/mame-libretro-9999 )
		mame2000? ( >=games-emulation/mame2000-libretro-9999 )
		mame2003? ( >=games-emulation/mame2003-libretro-9999 )
		mame2003plus? ( >=games-emulation/mame2003plus-libretro-9999 )
		mame2010? ( >=games-emulation/mame2010-libretro-9999 )
		mame2015? ( >=games-emulation/mame2015-libretro-9999 )
		mame2016? ( >=games-emulation/mame2016-libretro-9999 )
		mednafen-gba? ( >=games-emulation/mednafen-gba-libretro-9999 )
		mednafen-lynx? ( >=games-emulation/mednafen-lynx-libretro-9999 )
		mednafen-ngp? ( >=games-emulation/mednafen-ngp-libretro-9999 )
		mednafen-pce-fast? ( >=games-emulation/mednafen-pce-fast-libretro-9999 )
		mednafen-pcfx? ( >=games-emulation/mednafen-pcfx-libretro-9999 )
		mednafen-psx? ( >=games-emulation/mednafen-psx-libretro-9999 )
		mednafen-saturn? ( >=games-emulation/mednafen-saturn-libretro-9999 )
		mednafen-snes? ( >=games-emulation/mednafen-snes-libretro-9999 )
		mednafen-supergrafx? ( >=games-emulation/mednafen-supergrafx-libretro-9999 )
		mednafen-vb? ( >=games-emulation/mednafen-vb-libretro-9999 )
		mednafen-wswan? ( >=games-emulation/mednafen-wswan-libretro-9999 )
		melonds? ( >=games-emulation/melonds-libretro-9999 )
		meowpc98? ( >=games-emulation/meowpc98-libretro-9999 )
		meteor? ( >=games-emulation/meteor-libretro-9999 )
		mgba? ( || ( >=games-emulation/mgba-libretro-9999 >=games-emulation/mgba-libretro-cheevo-9999 ) )
		mrboom? ( >=games-emulation/mrboom-libretro-9999 )
		mupen64plus? ( >=games-emulation/mupen64plus-libretro-9999 )
		nestopia? ( >=games-emulation/nestopia-libretro-9999 )
		np2kai? ( >=games-emulation/np2kai-libretro-9999 )
		nxengine? ( >=games-emulation/nxengine-libretro-9999 )
		o2em? ( >=games-emulation/o2em-libretro-9999 )
		openlara? ( >=games-emulation/openlara-libretro-9999 )
		parallel-n64? ( >=games-emulation/parallel-n64-libretro-9999 )
		pcsx-rearmed? ( >=games-emulation/pcsx-rearmed-libretro-9999 )
		picodrive? ( >=games-emulation/picodrive-libretro-9999 )
		play? ( >=games-emulation/play-libretro-9999 )
		pokemini?  ( >=games-emulation/pokemini-libretro-9999 )
		ppsspp? ( >=games-emulation/ppsspp-libretro-9999 )
		prboom? ( >=games-emulation/prboom-libretro-9999 )
		prosystem? ( >=games-emulation/prosystem-libretro-9999 )
		px68k? ( >=games-emulation/px68k-libretro-9999 )
		quasi? ( >=games-emulation/quasi-libretro-9999 )
		quicknes? ( >=games-emulation/quicknes-libretro-9999 )
		redream? ( >=games-emulation/redream-libretro-9999 )
		reicast? ( >=games-emulation/reicast-libretro-9999 )
		reminiscence? ( >=games-emulation/reminiscence-libretro-9999 )
		sameboy? ( >=games-emulation/sameboy-libretro-9999 )
		scummvm? ( >=games-emulation/scummvm-libretro-9999 )
		snes9x? ( >=games-emulation/snes9x-libretro-9999 )
		snes9x2002? ( >=games-emulation/snes9x2002-libretro-9999 )
		snes9x2005? ( >=games-emulation/snes9x2005-libretro-9999 )
		snes9x2010? ( >=games-emulation/snes9x2010-libretro-9999 )
		stella? ( >=games-emulation/stella-libretro-9999 )
		tgbdual? ( >=games-emulation/tgbdual-libretro-9999 )
		theodore? ( >=games-emulation/theodore-libretro-9999 )
		thepowdertoy? ( >=games-emulation/thepowdertoy-libretro-9999 )
		tyrquake? ( >=games-emulation/tyrquake-libretro-9999 )
		vba-next? ( >=games-emulation/vba-next-libretro-9999 )
		vbam? ( >=games-emulation/vbam-libretro-9999 )
		vecx? ( >=games-emulation/vecx-libretro-9999 )
		vice? ( >=games-emulation/vice-libretro-9999 )
		virtualjaguar? ( >=games-emulation/virtualjaguar-libretro-9999 )
		xrick? ( >=games-emulation/xrick-libretro-9999 )
		yabause? ( >=games-emulation/yabause-libretro-9999 )"
DEPEND=""
